import type { Metadata } from "next";
import { Geist_Mono, M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";

const mPlusRounded1c = M_PLUS_Rounded_1c({
	variable: "--font-m-plus-rounded-1c",
	subsets: ["latin", "latin-ext"],
	weight: ["300", "400", "500", "700"],
});

// コードフォント
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning>
			<body
				className={`${mPlusRounded1c.variable} ${geistMono.variable} antialiased min-h-dvh text-balance`}
			>
				{children}
			</body>
		</html>
	);
}
